# Generated by Django 4.0.3 on 2022-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_following_chirp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followcount',
            field=models.IntegerField(default=0),
        ),
    ]
